---
title: "Advanced Web Technologies"
author: "Ruhan, Julio, Vinzenz"
date: "24 11 21"
output: pdf_document
---

#InstallPackages 
```{r}
#Install packages, which are not yet installed
package <- c("dummies","ggplot2","Metrics","GGally","dplyr","tidyr","forecast","ggmap","datetime","fpc")

installedPackages <- package %in% rownames(installed.packages())
if(any(installedPackages == FALSE)){
  install.packages(package[!installedPackages])
}

#FUNKTIONIERT NOCH NICHT ACHTUNG

```


#LoadPackages
```{r}
library("dummies")
library("ggplot2")
library("Metrics")
library("GGally")
library("dplyr")
library("tidyr")
library("forecast")
library("ggmap")
library("datetime")
library("fpc")
```

#DataLoad
```{r}

daten = read.csv2("pse_data.csv",sep=",")

```

#CharIntoNum
```{r}

daten$s_scan_typeNumber = ifelse(daten$s_scan_type =="progressive",1,0)



```

#summaryData
```{r}

summary(daten)
str(daten)
head(daten)



```

#DataClearing
```{r}
#chr --> num 
daten$c_si = as.numeric(daten$c_si)

#chr --> num 
daten$c_ti = as.numeric(daten$c_ti)

#chr --> num 
daten$c_scene_change_ffmpeg_ratio30 = as.numeric(daten$c_scene_change_ffmpeg_ratio30)

#chr --> num 
daten$c_scene_change_ffmpeg_ratio60 = as.numeric(daten$c_scene_change_ffmpeg_ratio60)

#chr --> num 
daten$c_scene_change_ffmpeg_ratio90 = as.numeric(daten$c_scene_change_ffmpeg_ratio90)

#chr --> num 
daten$c_colorhistogram_mean_dark = as.numeric(daten$c_colorhistogram_mean_dark)

#chr --> num 
daten$c_colorhistogram_mean_medium_dark = as.numeric(daten$c_colorhistogram_mean_medium_dark)

#chr --> num 
daten$c_colorhistogram_mean_medium_bright = as.numeric(daten$c_colorhistogram_mean_medium_bright)

#chr --> num 
daten$c_colorhistogram_mean_bright = as.numeric(daten$c_colorhistogram_mean_bright)

#chr --> num 
daten$c_colorhistogram_std_dev_medium_dark = as.numeric(daten$c_colorhistogram_std_dev_medium_dark)

#chr --> num 
daten$c_colorhistogram_std_dev_dark = as.numeric(daten$c_colorhistogram_std_dev_dark)

#chr --> num 
daten$c_colorhistogram_std_dev_medium_bright = as.numeric(daten$c_colorhistogram_std_dev_medium_bright)

#chr --> num 
daten$c_colorhistogram_std_dev_bright = as.numeric(daten$c_colorhistogram_std_dev_bright)

#chr --> num 
daten$c_colorhistogram_temporal_mean_std_dev_dark = as.numeric(daten$c_colorhistogram_temporal_mean_std_dev_dark)

#chr --> num 
daten$c_colorhistogram_temporal_mean_std_dev_medium_dark = as.numeric(daten$c_colorhistogram_temporal_mean_std_dev_medium_dark)

#chr --> num 
daten$c_colorhistogram_temporal_mean_std_dev_medium_bright = as.numeric(daten$c_colorhistogram_temporal_mean_std_dev_medium_bright)

#chr --> num 
daten$c_colorhistogram_temporal_mean_std_dev_bright = as.numeric(daten$c_colorhistogram_temporal_mean_std_dev_bright)

#chr --> num
daten$t_average_vmaf = as.numeric(daten$t_average_vmaf)

#chr --> num 
daten$e_framerate = as.numeric(daten$e_framerate)

#chr --> num 
daten$e_gop_size = as.numeric(daten$e_gop_size)

#chr --> num 
daten$e_bit_depth = as.numeric(daten$e_bit_depth)

#int --> factor 
daten$ï..s_video_id = as.factor(daten$ï..s_video_id)

#char --> factor 
daten$e_aspect_ratio = as.factor(daten$e_aspect_ratio)

#char --> factor 
daten$e_pixel_aspect_ratio = as.factor(daten$e_pixel_aspect_ratio)

#char --> factor 
daten$s_scan_type = as.factor(daten$s_scan_type)

#char --> factor 
daten$c_content_category = as.factor(daten$c_content_category)

#char --> factor 
daten$e_codec = as.factor(daten$e_codec)

#char --> factor 
daten$e_codec_profile = as.factor(daten$e_codec_profile)

#char --> factor 
daten$e_scan_type = as.factor(daten$e_scan_type)

#char --> factor 
daten$e_pixel_fmt = as.factor(daten$e_pixel_fmt)


#int --> num
daten$s_width = as.numeric(daten$s_width)

#int --> num
daten$s_height = as.numeric(daten$s_height)

#int --> num
daten$s_storage_size = as.numeric(daten$s_storage_size)

#int --> num
daten$s_duration = as.numeric(daten$s_duration)

#int --> num
daten$c_scene_change_py_thresh30 = as.numeric(daten$c_scene_change_py_thresh30)

#int --> num
daten$c_scene_change_py_thresh50 = as.numeric(daten$c_scene_change_py_thresh50)

#int --> num
daten$e_crf = as.numeric(daten$e_crf)

#int --> num
daten$e_width = as.numeric(daten$e_width)

#int --> num
daten$e_height = as.numeric(daten$e_height)

#int --> num
daten$e_codec_level = as.numeric(daten$e_codec_level)

#int --> num
daten$e_b_frame_int = as.numeric(daten$e_b_frame_int)

#int --> num
daten$e_ref_frame_count = as.numeric(daten$e_ref_frame_count)

#int --> num
daten$t_average_bitrate = as.numeric(daten$t_average_bitrate)


#char --> num
daten$s_scan_typeNumber = ifelse(daten$s_scan_type =="progressive",1,0)

#char --> num
daten$c_content_categoryNumber = ifelse(daten$c_content_category =="ballplayer",1,ifelse(daten$c_content_category =="alp",2,ifelse(daten$c_content_category =="black widow",3,ifelse(daten$c_content_category =="breastplate",4,ifelse(daten$c_content_category =="bubble",5,ifelse(daten$c_content_category =="cliff",6,ifelse(daten$c_content_category =="comic book",7,ifelse(daten$c_content_category =="crutch",8,ifelse(daten$c_content_category =="dogsled",9,ifelse(daten$c_content_category =="fountain",10,ifelse(daten$c_content_category =="geyser",11,ifelse(daten$c_content_category =="grille",12,ifelse(daten$c_content_category =="lawn mower",13,ifelse(daten$c_content_category =="maypole",14,ifelse(daten$c_content_category =="parachute",15,ifelse(daten$c_content_category =="pier",16,ifelse(daten$c_content_category =="shopping cart",17,ifelse(daten$c_content_category =="ski",18,ifelse(daten$c_content_category =="spider web",19,ifelse(daten$c_content_category =="sports car",20,ifelse(daten$c_content_category =="spotlight",21,ifelse(daten$c_content_category =="swing",22,ifelse(daten$c_content_category =="tile roof",23,ifelse(daten$c_content_category =="trimaran",24,0))))))))))))))))))))))))

#char --> num
daten$e_codec_profileNumber = ifelse(daten$e_codec_profile =="high",2,ifelse(daten$e_codec_profile =="main",1,0))

#char --> num
daten$e_scan_typeNumber = ifelse(daten$e_scan_type =="progressive",1,ifelse(daten$e_scan_type =="interlaced",2,0))


#char --> num
daten$e_pixel_fmtNumber = ifelse(daten$e_pixel_fmt =="yuv420p",1,0)



str(daten)
head(daten)
summary(daten)




```

#DataVisualization
```{r}



```

#CorrelationTowardsVMAF
```{r}

#Correlation of all Variables toward VMAF

korrelation = data.frame(round(cor(daten[,c("s_width","s_height","s_storage_size","s_duration","c_si","c_ti","c_scene_change_ffmpeg_ratio30","c_scene_change_ffmpeg_ratio60","c_scene_change_ffmpeg_ratio90","c_scene_change_py_thresh30","c_scene_change_py_thresh50","c_colorhistogram_mean_dark","c_colorhistogram_mean_medium_dark","c_colorhistogram_mean_medium_bright","c_colorhistogram_mean_bright","c_colorhistogram_std_dev_dark","c_colorhistogram_std_dev_medium_dark","c_colorhistogram_std_dev_medium_bright","c_colorhistogram_std_dev_bright","c_colorhistogram_temporal_mean_std_dev_dark","c_colorhistogram_temporal_mean_std_dev_medium_dark","c_colorhistogram_temporal_mean_std_dev_medium_bright","c_colorhistogram_temporal_mean_std_dev_bright","e_crf","e_width","e_height","e_codec_level","e_framerate","e_gop_size","e_b_frame_int","e_ref_frame_count","e_bit_depth","t_average_bitrate","s_scan_typeNumber","c_content_categoryNumber","e_codec_profileNumber","e_scan_typeNumber")],daten$t_average_vmaf,use="complete.obs"),3))
colnames(korrelation)= c("Korrelation")

korrelation

#top10
korrelationTop10 <- head(korrelation %>% arrange(desc(abs(korrelation$Korrelation))),10)
korrelationTop10

```

#
```{r}
cat("The highest correlations are: e_crf, t_average_bitrate, e_width, e_height, e_codec_level, e_scan_typeNumber, e_codec_profileNumber")

ggpairs(daten[, c("e_crf","t_average_bitrate", "e_width", "e_height", "e_codec_level","e_scan_typeNumber","e_codec_profileNumber")], 
        progress = FALSE,
        lower = list(continuous = wrap("smooth_loess", colour = "aquamarine2")))

cat("All Graphs look good, so we can use all of the variables in the Model")

```
#Modell
```{r}

#Basline = PSNR = MAE (look at the one Paper, have to search which one it was)
daten$Baseline = mean(daten$t_average_vmaf)

#using sMAPE for a better testing
#New Data Frame
evaluation = data.frame(Model = "Baseline", 
                        MAE = numeric(1),
                        sMAPE = numeric(1))

#MAE calculate
evaluation[evaluation$Model == "Baseline",]$MAE = round(mae(daten$t_average_vmaf,daten$Baseline),4)
#sMAPE calculate
evaluation[evaluation$Model == "Baseline",]$sMAPE = round(smape(daten$t_average_vmaf,daten$Baseline),4)

#selecting a random seed
set.seed(4141)

#select a random part 80%
random = sample(1:nrow(daten),nrow(daten)*0.8)

#random selected goes into the training
datenTraining = daten[random, ]

#show the head of the training set
head(datenTraining)

#the other Part of random goes into the Tester
datenTest = daten[-random, ]

#show the head of test set
head(datenTest)

#Start with the Univariant Model
Modell1 = lm(t_average_vmaf ~ e_crf, data = datenTraining)
summary(Modell1)

Modell2 = lm(t_average_vmaf ~ t_average_bitrate, data = datenTraining)
summary(Modell2)

Modell3 = lm(t_average_vmaf ~ e_width, data = datenTraining)
summary(Modell3)

Modell4 = lm(t_average_vmaf ~ e_height, data = datenTraining)
summary(Modell4)

Modell5 = lm(t_average_vmaf ~ e_codec_level, data = datenTraining)
summary(Modell5)

Modell6 = lm(t_average_vmaf ~ e_scan_typeNumber, data = datenTraining)
summary(Modell6)

Modell7 = lm(t_average_vmaf ~ e_codec_profileNumber, data = datenTraining)
summary(Modell7)

#Residuenplot 1
ggplot(data = NULL, aes(x= Modell1$model$e_crf, y = Modell1$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 2
ggplot(data = NULL, aes(x= Modell2$model$t_average_bitrate, y = Modell2$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 3
ggplot(data = NULL, aes(x= Modell3$model$e_width, y = Modell3$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 4
ggplot(data = NULL, aes(x= Modell4$model$e_height, y = Modell4$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 5
ggplot(data = NULL, aes(x= Modell5$model$e_codec_level, y = Modell5$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 6
ggplot(data = NULL, aes(x= Modell6$model$e_scan_typeNumber, y = Modell6$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

#Residuenplot 7
ggplot(data = NULL, aes(x= Modell7$model$e_codec_profileNumber, y = Modell7$residuals)) +
  geom_point() +
  geom_smooth(se = FALSE, method = loess)

cat("the residuen Plot for codec and codecProfileNumber are not perfect, but they are good enough for our module")

#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell1","Modell2","Modell3","Modell4","Modell5","Modell6","Modell7"),
                                          MAE = numeric(7),
                                          sMAPE = numeric(7)))

#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell1",]$MAE = round(mae(Modell1$model$t_average_vmaf,Modell1$fitted.values),4)

evaluation[evaluation$Model == "Modell2",]$MAE = round(mae(Modell2$model$t_average_vmaf,Modell2$fitted.values),4)

evaluation[evaluation$Model == "Modell3",]$MAE = round(mae(Modell3$model$t_average_vmaf,Modell3$fitted.values),4)

evaluation[evaluation$Model == "Modell4",]$MAE = round(mae(Modell4$model$t_average_vmaf,Modell4$fitted.values),4)

evaluation[evaluation$Model == "Modell5",]$MAE = round(mae(Modell5$model$t_average_vmaf,Modell5$fitted.values),4)

evaluation[evaluation$Model == "Modell6",]$MAE = round(mae(Modell6$model$t_average_vmaf,Modell6$fitted.values),4)

evaluation[evaluation$Model == "Modell7",]$MAE = round(mae(Modell7$model$t_average_vmaf,Modell7$fitted.values),4)


#sMAPE calculation
evaluation[evaluation$Model == "Modell1",]$sMAPE = round(smape(Modell1$model$t_average_vmaf,Modell1$fitted.values),4)

evaluation[evaluation$Model == "Modell2",]$sMAPE = round(smape(Modell2$model$t_average_vmaf,Modell2$fitted.values),4)

evaluation[evaluation$Model == "Modell3",]$sMAPE = round(smape(Modell3$model$t_average_vmaf,Modell3$fitted.values),4)

evaluation[evaluation$Model == "Modell4",]$sMAPE = round(smape(Modell4$model$t_average_vmaf,Modell4$fitted.values),4)

evaluation[evaluation$Model == "Modell5",]$sMAPE = round(smape(Modell5$model$t_average_vmaf,Modell5$fitted.values),4)

evaluation[evaluation$Model == "Modell6",]$sMAPE = round(smape(Modell6$model$t_average_vmaf,Modell6$fitted.values),4)

evaluation[evaluation$Model == "Modell7",]$sMAPE = round(smape(Modell7$model$t_average_vmaf,Modell7$fitted.values),4)


evaluation

cat("The modell1 has the best MAE and sMAPE, therefore we are going to continue with them")

#Bivariants
Modell12 = lm(t_average_vmaf ~ e_crf + t_average_bitrate, data = datenTraining)
summary(Modell12)

Modell13 = lm(t_average_vmaf ~ e_crf + e_width, data = datenTraining)
summary(Modell13)

Modell14 = lm(t_average_vmaf ~ e_crf + e_height, data = datenTraining)
summary(Modell14)

Modell15 = lm(t_average_vmaf ~ e_crf + e_codec_level, data = datenTraining)
summary(Modell15)

Modell16 = lm(t_average_vmaf ~ e_crf + e_scan_typeNumber, data = datenTraining)
summary(Modell16)

Modell17 = lm(t_average_vmaf ~ e_crf + e_codec_profileNumber, data = datenTraining)
summary(Modell17)


cat("all of them are significant, so we can go on")

#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell12","Modell13","Modell14","Modell15","Modell16","Modell17"),
                                          MAE = numeric(6),
                                          sMAPE = numeric(6)))


#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell12",]$MAE = round(mae(Modell12$model$t_average_vmaf,Modell12$fitted.values),4)

evaluation[evaluation$Model == "Modell13",]$MAE = round(mae(Modell13$model$t_average_vmaf,Modell13$fitted.values),4)

evaluation[evaluation$Model == "Modell14",]$MAE = round(mae(Modell14$model$t_average_vmaf,Modell14$fitted.values),4)

evaluation[evaluation$Model == "Modell15",]$MAE = round(mae(Modell15$model$t_average_vmaf,Modell15$fitted.values),4)

evaluation[evaluation$Model == "Modell16",]$MAE = round(mae(Modell16$model$t_average_vmaf,Modell16$fitted.values),4)

evaluation[evaluation$Model == "Modell17",]$MAE = round(mae(Modell17$model$t_average_vmaf,Modell17$fitted.values),4)


#sMAPE calculation
evaluation[evaluation$Model == "Modell12",]$sMAPE = round(smape(Modell12$model$t_average_vmaf,Modell12$fitted.values),4)

evaluation[evaluation$Model == "Modell13",]$sMAPE = round(smape(Modell13$model$t_average_vmaf,Modell13$fitted.values),4)

evaluation[evaluation$Model == "Modell14",]$sMAPE = round(smape(Modell14$model$t_average_vmaf,Modell14$fitted.values),4)

evaluation[evaluation$Model == "Modell15",]$sMAPE = round(smape(Modell15$model$t_average_vmaf,Modell15$fitted.values),4)

evaluation[evaluation$Model == "Modell16",]$sMAPE = round(smape(Modell16$model$t_average_vmaf,Modell16$fitted.values),4)

evaluation[evaluation$Model == "Modell17",]$sMAPE = round(smape(Modell17$model$t_average_vmaf,Modell17$fitted.values),4)

evaluation


cat("Modell13 has the best value, therefore we are going to go on with that model")

#Bivariants
Modell132 = lm(t_average_vmaf ~ e_crf + e_width + t_average_bitrate, data = datenTraining)
summary(Modell132)

Modell134 = lm(t_average_vmaf ~ e_crf + e_width + e_height, data = datenTraining)
summary(Modell134)

Modell135 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_level, data = datenTraining)
summary(Modell135)

Modell136 = lm(t_average_vmaf ~ e_crf + e_width + e_scan_typeNumber, data = datenTraining)
summary(Modell136)

Modell137 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber, data = datenTraining)
summary(Modell137)

cat("All significant")

#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell132","Modell134","Modell135","Modell136","Modell137"),
                                          MAE = numeric(5),
                                          sMAPE = numeric(5)))

#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell132",]$MAE = round(mae(Modell132$model$t_average_vmaf,Modell132$fitted.values),4)

evaluation[evaluation$Model == "Modell134",]$MAE = round(mae(Modell134$model$t_average_vmaf,Modell134$fitted.values),4)

evaluation[evaluation$Model == "Modell135",]$MAE = round(mae(Modell135$model$t_average_vmaf,Modell135$fitted.values),4)

evaluation[evaluation$Model == "Modell136",]$MAE = round(mae(Modell136$model$t_average_vmaf,Modell136$fitted.values),4)

evaluation[evaluation$Model == "Modell137",]$MAE = round(mae(Modell137$model$t_average_vmaf,Modell137$fitted.values),4)

#sMAPE calculation
evaluation[evaluation$Model == "Modell132",]$sMAPE = round(smape(Modell132$model$t_average_vmaf,Modell132$fitted.values),4)

evaluation[evaluation$Model == "Modell134",]$sMAPE = round(smape(Modell134$model$t_average_vmaf,Modell134$fitted.values),4)

evaluation[evaluation$Model == "Modell135",]$sMAPE = round(smape(Modell135$model$t_average_vmaf,Modell135$fitted.values),4)

evaluation[evaluation$Model == "Modell136",]$sMAPE = round(smape(Modell136$model$t_average_vmaf,Modell136$fitted.values),4)

evaluation[evaluation$Model == "Modell137",]$sMAPE = round(smape(Modell137$model$t_average_vmaf,Modell137$fitted.values),4)

evaluation

cat("Modell137 has the best value, therefore we are going to continue with that")


#Bivariants
Modell1372 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber + t_average_bitrate, data = datenTraining)
summary(Modell1372)

Modell1374 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber +  e_height, data = datenTraining)
summary(Modell1374)

Modell1375 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber +  e_codec_level, data = datenTraining)
summary(Modell1375)

Modell1376 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber + e_scan_typeNumber, data = datenTraining)
summary(Modell1376)



cat("All significant")


#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell1372","Modell1374","Modell1375","Modell1376"),
                                          MAE = numeric(4),
                                          sMAPE = numeric(4)))

#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell1372",]$MAE = round(mae(Modell1372$model$t_average_vmaf,Modell1372$fitted.values),4)

evaluation[evaluation$Model == "Modell1374",]$MAE = round(mae(Modell1374$model$t_average_vmaf,Modell1374$fitted.values),4)

evaluation[evaluation$Model == "Modell1375",]$MAE = round(mae(Modell1375$model$t_average_vmaf,Modell1375$fitted.values),4)

evaluation[evaluation$Model == "Modell1376",]$MAE = round(mae(Modell1376$model$t_average_vmaf,Modell1376$fitted.values),4)


#sMAPE calculation
evaluation[evaluation$Model == "Modell1372",]$sMAPE = round(smape(Modell1372$model$t_average_vmaf,Modell1372$fitted.values),4)

evaluation[evaluation$Model == "Modell1374",]$sMAPE = round(smape(Modell1374$model$t_average_vmaf,Modell1374$fitted.values),4)

evaluation[evaluation$Model == "Modell1375",]$sMAPE = round(smape(Modell1375$model$t_average_vmaf,Modell1375$fitted.values),4)

evaluation[evaluation$Model == "Modell1376",]$sMAPE = round(smape(Modell1376$model$t_average_vmaf,Modell1376$fitted.values),4)



evaluation

cat("Modell1375 has the best value, therefore we are going to continue with that")


#Bivariants
Modell13752 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber + e_codec_level + t_average_bitrate, data = datenTraining)
summary(Modell13752)

Modell13754 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber +  e_codec_level + e_height, data = datenTraining)
summary(Modell13754)


Modell13756 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber  + e_codec_level +e_scan_typeNumber, data = datenTraining)
summary(Modell13756)


cat("All significant")


#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell13752","Modell13754","Modell13756"),
                                          MAE = numeric(3),
                                          sMAPE = numeric(3)))

#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell13752",]$MAE = round(mae(Modell13752$model$t_average_vmaf,Modell13752$fitted.values),4)

evaluation[evaluation$Model == "Modell13754",]$MAE = round(mae(Modell13754$model$t_average_vmaf,Modell13754$fitted.values),4)

evaluation[evaluation$Model == "Modell13756",]$MAE = round(mae(Modell13756$model$t_average_vmaf,Modell13756$fitted.values),4)


#sMAPE calculation
evaluation[evaluation$Model == "Modell13752",]$sMAPE = round(smape(Modell13752$model$t_average_vmaf,Modell13752$fitted.values),4)

evaluation[evaluation$Model == "Modell13754",]$sMAPE = round(smape(Modell13754$model$t_average_vmaf,Modell13754$fitted.values),4)

evaluation[evaluation$Model == "Modell13756",]$sMAPE = round(smape(Modell13756$model$t_average_vmaf,Modell13756$fitted.values),4)

evaluation

cat("Modell13756 has the best value, therefore we are going to continue with that")

#Bivariants
Modell137562 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber + e_codec_level + e_scan_typeNumber +t_average_bitrate, data = datenTraining)
summary(Modell137562)

Modell137564 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber +  e_codec_level + e_scan_typeNumber + e_height, data = datenTraining)
summary(Modell137564)


cat("All significant")


#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell137562","Modell137564"),
                                          MAE = numeric(2),
                                          sMAPE = numeric(2)))


#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell137562",]$MAE = round(mae(Modell137562$model$t_average_vmaf,Modell137562$fitted.values),4)

evaluation[evaluation$Model == "Modell137564",]$MAE = round(mae(Modell137564$model$t_average_vmaf,Modell137564$fitted.values),4)

#sMAPE calculation
evaluation[evaluation$Model == "Modell137562",]$sMAPE = round(smape(Modell137562$model$t_average_vmaf,Modell137562$fitted.values),4)

evaluation[evaluation$Model == "Modell137564",]$sMAPE = round(smape(Modell137564$model$t_average_vmaf,Modell137564$fitted.values),4)

evaluation

cat("Modell137564 has the same value than Model1357, but we are still going to continue, because the sMape is minimal better.")


#Bivariants
Modell1375642 = lm(t_average_vmaf ~ e_crf + e_width + e_codec_profileNumber + e_codec_level + e_scan_typeNumber +t_average_bitrate + e_height, data = datenTraining)
summary(Modell1375642)

cat("Significant")


#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("Modell1375642"),
                                          MAE = numeric(1),
                                          sMAPE = numeric(1)))



#MAE=PSNR Calculation
evaluation[evaluation$Model == "Modell1375642",]$MAE = round(mae(Modell1375642$model$t_average_vmaf,Modell1375642$fitted.values),4)

#sMAPE calculation
evaluation[evaluation$Model == "Modell1375642",]$sMAPE = round(smape(Modell1375642$model$t_average_vmaf,Modell1375642$fitted.values),4)

evaluation

cat("Modell1375642 isnt better than the other Modell, therefore we can use Modell137564 as our Modell. So we have the Variables: /n 
    e_crf + e_width + e_codec_profileNumber +  e_codec_level + e_scan_typeNumber + e_height")


#__________________________________________________________________________________________________________________________________________________________________________________________________

prediction = predict(Modell137564, datenTest)
prediction

cat("now we have to test for overfitting: ")

#DataFrame extend
evaluation = rbind(evaluation, data.frame(Model = c("TestModell137564"),
                                          MAE = numeric(1),
                                          sMAPE = numeric(1)))


#MAE=PSNR Calculation
evaluation[evaluation$Model == "TestModell137564",]$MAE = round(mae(datenTest$t_average_vmaf,prediction),4)

#sMAPE calculation
evaluation[evaluation$Model == "TestModell137564",]$sMAPE = round(smape(datenTest$t_average_vmaf,prediction),4)

evaluation

cat("The test Model has a slightly worse MAE but an better sMAPE, therefore there is no overfitting and this modell can be used :) ")

```

#Prediction
```{r}

predicitionVMAF <- predict(Modell137564, daten, interval = "confidence", level = 0.99)
predicitionVMAF <- data.frame(predicitionVMAF)

acurateVMAF <- cbind(daten[,c(1,43)],predicitionVMAF)
acurateVMAF

daten$vmafPredicted = predicitionVMAF$fit


```


#ConvexHullFertigeSchnipsel
```{r}

#funktioniert
for(i in unique(daten$ï..s_video_id)) {
  gi <-
    ggplot(
      aes(
        x = t_average_bitrate,
        y = vmafPredicted,
        colour = as.factor(e_height)
      ),
      data = subset(daten,  ï..s_video_id == i)
    ) +
    labs(
      title = sprintf("Convex Hull"),
      subtitle = daten[daten$ï..s_video_id == i, ]$ï..s_video_id,
      caption = if (daten[daten$ï..s_video_id == i, ]$c_content_category == "") {
        "No Content Category"
      } else{
        daten[daten$ï..s_video_id == i, ]$c_content_category
      },
      x = "Bitrate",
      y = "vmaf Predicted"
    ) +
    geom_line()
  
  print(gi)
  
  #ggsave(filename = sprintf('%sa.png', i), plot = gi)
}


```

#getConvexHullNumbers
```{r}

#1) new table with the highest vmaf for the every bitrate 
  #for jede videoId
  #add new tabelle
  #highestVmaf for every bitrate intervall [0-235, 236-480...]
  #add line to the other graph

#TabelleIntervalle: 235,375,560,750,1050,1750,2350,3000,4300,5800
daten$bitrate = ifelse(daten$t_average_bitrate<235,235, ifelse(daten$t_average_bitrate<375,375,ifelse(daten$t_average_bitrate<560,560, ifelse(daten$t_average_bitrate<750,750, ifelse(daten$t_average_bitrate<1050,1050, ifelse(daten$t_average_bitrate<1750,1750,ifelse(daten$t_average_bitrate<2350,2350,ifelse(daten$t_average_bitrate<3000,3000,ifelse(daten$t_average_bitrate<4300,4300,ifelse(daten$t_average_bitrate<5800,5800,5800))))))))))

#ConvexHullWerte

encodingLadder <- as.data.frame(
daten %>%
  group_by(ï..s_video_id, bitrate) %>%
  summarise(maxVMAF = max(vmafPredicted, .groups = FALSE)))

#fertig
daten = merge(daten, encodingLadder, by=c("ï..s_video_id","bitrate"), all = T)

encodingLadderFinished <- as.data.frame(
  daten %>%
  group_by(ï..s_video_id, bitrate, maxVMAF) %>%
  summarise(resolution = max(e_height, .groups = FALSE)))

encodingLadderFinished$resolution = ifelse(encodingLadderFinished$resolution == 234,'416x234',ifelse(encodingLadderFinished$resolution == 540,'960x540',ifelse(encodingLadderFinished$resolution == 360,'640x360',ifelse(encodingLadderFinished$resolution == 432,'768x432',ifelse(encodingLadderFinished$resolution == 720,'1280x720',ifelse(encodingLadderFinished$resolution == 1080,'1920x1080','fehler'))))))

encodingLadderFinished <- encodingLadderFinished[,c("ï..s_video_id","bitrate","resolution","maxVMAF")]

encodingLadderFinished




for(i in unique(daten$ï..s_video_id)) {
  gi <- ggplot(aes(
        x = t_average_bitrate,
        y = maxVMAF,
        colour = "ConvexHull",
        ymin = 0
      ),
      data = subset(daten,  ï..s_video_id == i)
    ) +
    labs(
      title = sprintf("Convex Hull"),
      subtitle = daten[daten$ï..s_video_id == i, ]$ï..s_video_id,
      caption = if (daten[daten$ï..s_video_id == i, ]$c_content_category == "") {
        "No Content Category"
      } else{
        daten[daten$ï..s_video_id == i, ]$c_content_category
      },
      x = "Bitrate",
      y = "vmaf Predicted"
    ) +
    geom_line()
  
  gi2 <- ggplot(aes(
        x = t_average_bitrate,
        y = maxVMAF,
        colour = "ConvexHull",
        ymin = 0,
        ymax = 120,
        xmax = 7000,
        xmin = 0
      ),
      data = subset(daten,  ï..s_video_id == i)
    ) +
    labs(
      title = sprintf("Convex Hull"),
      subtitle = daten[daten$ï..s_video_id == i, ]$ï..s_video_id,
      caption = if (daten[daten$ï..s_video_id == i, ]$c_content_category == "") {
        "No Content Category"
      } else{
        daten[daten$ï..s_video_id == i, ]$c_content_category
      },
      x = "Bitrate",
      y = "vmaf Predicted"
    ) +
    geom_line()
  
  print(gi)
  print(gi2)
  
  #ggsave(filename = sprintf('%s.png', i), plot = gi)
}


```
